### ISSUE TITLE
Action now breaks with 'get_image_info'

### ISSUE THREAD

**Issue by vpetersson** [maggie0002/balena-cli-action#1]
This action worked smooth for us some time, but has broken in the last few weeks. Logs can be found [here](https://github.com/Screenly/Anthias/actions/runs/3630742959/jobs/6124470603). 

This appears to be where the issue breaks:

```
An error has occurred executing internal preload command 'get_image_info':
{"command":"get_image_info","parameters":{}}
```

We haven't really changed anything in our code base related to this, and it doesn't appear as any changes has been pushed to this repo either, suggesting that it breaks due to some changes either in balena-cli or in GitHub's Worker infra.

[Relevant conversation for context](https://forums.balena.io/t/building-disk-images-i-e-preloading-with-github-action-fails/365245)

**Comment by maggie44** [comment]
It looks like it is an issue with the preloader on the latest Ubuntu version, rather than this CLI action. 

An issue will need to be created for the preloader instead, and I have updated the docs examples to pin to the current ubuntu version that should resolve the issue for this CLI in the meantime: https://github.com/balena-labs-research/community-cli-action/commit/540754692e8560313b752b069972209ceb1c9c3a

**Comment by vpetersson** [comment]
Yep. Worked. Details [here](https://forums.balena.io/t/building-disk-images-i-e-preloading-with-github-action-fails/365245/19?u=vpetersson).
